export const category = [
  "Fiction",
  "Nonfiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Science Fiction",
  "Fantasy",
  "Horror",
  "Biography",
  "History",
  "Self-help",
  "Poetry",
  "Children",
  "Young Adult",
  "Crime",
  "Adventure",
  "Comedy",
  "Drama",
  "Graphic Novel",
  "Science",
];
